import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
import type {Pool} from 'pg';
import {readConfig} from '../shared/config';
import {makePool} from '../shared/database';
import {buildApp} from '../api/app';
import {type Command} from '../../packages/contracts/index';
import {runOne} from '../worker/runner';
import {createHash} from 'node:crypto';
const config=readConfig();
for(const endpoint of [config.SUPABASE_URL,config.DATABASE_URL])if(!['127.0.0.1','localhost','[::1]'].includes(new URL(endpoint).hostname))throw new Error('Integration tests require both Supabase and Postgres to use isolated loopback endpoints');
let app:Awaited<ReturnType<typeof buildApp>>,pool:Pool,admin:SupabaseClient;
const users:Record<string,{id:string;token:string;deviceId:string}>={};let org:string,otherOrg:string,tripId=crypto.randomUUID(),authId=crypto.randomUUID(),docId=crypto.randomUUID(),expenseId=crypto.randomUUID(),voucherId=crypto.randomUUID();
const request=async(user:string,method:string,url:string,payload?:unknown)=>{const r=await app.inject({method:method as any,url,headers:{authorization:`Bearer ${users[user].token}`},payload:payload as any});return {status:r.statusCode,body:r.json()}};
function command(type:string,id:string,version:number,payload:unknown,organizationId=org):Command{return {type,entityId:id,expectedVersion:version,payload,organizationId,commandId:crypto.randomUUID(),deviceId:users.traveler.deviceId,schemaVersion:1} as Command}
const send=async(user:string,c:Command)=>request(user,'POST','/v1/commands',{...c,deviceId:users[user].deviceId});
beforeAll(async()=>{
 pool=makePool(config);admin=createClient(config.SUPABASE_URL,config.SUPABASE_SECRET_KEY,{auth:{persistSession:false}});app=await buildApp({...config,APPROVAL_MODE:'required'},{pool,logger:false});
 for(const name of ['traveler','reviewer','approver','outsider']){const email=`${name}-${crypto.randomUUID()}@ouranos.test`,password=`Local-${crypto.randomUUID()}!`;const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true});if(error)throw error;const client=createClient(config.SUPABASE_URL,config.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false}});const session=await client.auth.signInWithPassword({email,password});if(session.error)throw session.error;users[name]={id:data.user.id,token:session.data.session!.access_token,deviceId:crypto.randomUUID()}}
 const created=await request('traveler','POST','/v1/organizations',{name:'Integration fixtures'});expect(created.status,JSON.stringify(created.body)).toBe(201);org=created.body.id;
 otherOrg=(await request('outsider','POST','/v1/organizations',{name:'Other tenant'})).body.id;
 for(const role of ['reviewer','approver']){const result=await request('traveler','PUT',`/v1/organizations/${org}/members`,{userId:users[role].id,role});expect(result.status,JSON.stringify(result.body)).toBe(200)}
},60000);
afterAll(async()=>{await app?.close();await pool?.end()});
describe('real Postgres/Auth/Storage workflow',()=>{
 it('requires authentication',async()=>expect((await app.inject({method:'GET',url:'/v1/session'})).statusCode).toBe(401));
 it('creates a trip, deduplicates retry, and rejects changed replay',async()=>{const c=command('trip.save',tripId,0,{destination:'Washington',departure:'2026-10-12',returnDate:'2026-10-15',purpose:'Fixture',timezone:'UTC'});const first=await send('traveler',c);expect(first.status,JSON.stringify(first.body)).toBe(200);expect(first.body.entity.version).toBe(1);const retry=await send('traveler',c);expect(retry.body.replayed).toBe(true);const changed=await send('traveler',{...c,payload:{...c.payload,purpose:'Changed'}} as any);expect(changed.body.error.code).toBe('IDEMPOTENCY_CONFLICT')});
 it('enforces tenant isolation and read-only browser database access',async()=>{expect((await request('outsider','GET',`/v1/entities/trip/${tripId}?organizationId=${org}`)).status).toBe(404);const foreign=await send('outsider',command('authorization.save',crypto.randomUUID(),0,{tripId,formSchemaVersion:'ouranos.fixture.v1',formData:{purpose:'bad'}},otherOrg));expect(foreign.body.error.code).toBe('PERMISSION_DENIED');const direct=createClient(config.SUPABASE_URL,config.SUPABASE_PUBLISHABLE_KEY,{global:{headers:{Authorization:`Bearer ${users.traveler.token}`}}});const {error}=await direct.from('trips').update({status:'completed'}).eq('id',tripId);expect(error).toBeTruthy()});
 it('returns conflicts instead of overwriting stale versions',async()=>{const result=await send('traveler',command('trip.save',tripId,0,{destination:'Boston',departure:'2026-10-12',returnDate:'2026-10-15',purpose:'Stale'}));expect(result.body.error.code).toBe('VERSION_CONFLICT')});
 it('configures routing and submits a frozen authorization',async()=>{for(const kind of ['authorization','voucher']){const r=await send('traveler',command('workflow.configure',crypto.randomUUID(),0,{kind,name:'Fixture routing',steps:[{assigneeId:users.reviewer.id,role:'reviewer'},{assigneeId:users.approver.id,role:'approver'}]}));expect(r.status,JSON.stringify(r.body)).toBe(200)}const save=await send('traveler',command('authorization.save',authId,0,{tripId,formSchemaVersion:'ouranos.fixture.v1',formData:{purpose:'Test authorization'}}));expect(save.status,JSON.stringify(save.body)).toBe(200);const submit=await send('traveler',command('authorization.submit',authId,1,{}));expect(submit.status,JSON.stringify(submit.body)).toBe(200);expect(submit.body.entity.status).toBe('in_review');const edit=await send('traveler',command('authorization.save',authId,2,{tripId,formSchemaVersion:'ouranos.fixture.v1',formData:{purpose:'Changed'}}));expect(edit.body.error.code).toBe('INVALID_STATE_TRANSITION')});
 it('enforces routing order and preserves decisions',async()=>{const list=await request('reviewer','GET',`/v1/entities/approval?organizationId=${org}`);const a=list.body.entities[0];expect(a).toBeTruthy();const wrong=await send('approver',command('approval.decide',a.id,a.version,{decision:'approved'}));expect(wrong.body.error.code).toBe('PERMISSION_DENIED');const self=await send('traveler',command('approval.decide',a.id,a.version,{decision:'approved'}));expect(self.body.error.code).toBe('PERMISSION_DENIED');const first=await send('reviewer',command('approval.decide',a.id,a.version,{decision:'approved'}));expect(first.status,JSON.stringify(first.body)).toBe(200);const second=await send('approver',command('approval.decide',a.id,first.body.entity.version,{decision:'approved'}));expect(second.status,JSON.stringify(second.body)).toBe(200);expect(second.body.entity.status).toBe('approved');const history=await request('reviewer','GET',`/v1/approvals/${a.id}/revision?organizationId=${org}`);expect(history.body.decisions).toHaveLength(2);expect(history.body.revision.snapshot.entity.data.formData.purpose).toBe('Test authorization')});
 it('verifies uploaded bytes and processes receipts through provider adapters',async()=>{const bytes=Buffer.from('%PDF-1.7\nSynthetic receipt fixture\n');const sha256=createHash('sha256').update(bytes).digest('hex');const registered=await send('traveler',command('document.register',docId,0,{tripId,filename:'fixture.pdf',mediaType:'application/pdf',byteSize:bytes.length,sha256}));expect(registered.status,JSON.stringify(registered.body)).toBe(200);const upload=await request('traveler','POST',`/v1/documents/${docId}/upload`,{organizationId:org});expect(upload.status,JSON.stringify(upload.body)).toBe(200);const uploaded=await admin.storage.from('ouranos-documents').uploadToSignedUrl(upload.body.path,upload.body.token,bytes,{contentType:'application/pdf'});expect(uploaded.error).toBeNull();const finalized=await send('traveler',command('document.finalize',docId,1,{}));expect(finalized.status,JSON.stringify(finalized.body)).toBe(200);const jobKey=`receipt:${docId}:${finalized.body.entity.version}`;expect(await runOne(pool,admin,config,{scan:async()=>({clean:true}),extract:async()=>({modelVersion:'fixture-v1',fields:[{name:'total',value:'182.00',confidence:.98}]})},{organizationId:org,jobKey})).toBe(true);const processed=await request('traveler','GET',`/v1/entities/document/${docId}?organizationId=${org}`);expect(processed.body.entity.status).toBe('needs_review');expect((await request('outsider','POST',`/v1/documents/${docId}/download`,{organizationId:org})).status).toBe(404);const confirmed=await send('traveler',command('document.confirm',docId,processed.body.entity.version,{}));expect(confirmed.status,JSON.stringify(confirmed.body)).toBe(200)});
 it('connects an expense and voucher to the same trip without verifying a legacy form',async()=>{expect((await send('traveler',command('expense.save',expenseId,0,{tripId,merchant:'Hotel',incurredOn:'2026-10-12',amountMinor:18200,currency:'USD',category:'lodging',documentIds:[docId]}))).status).toBe(200);const save=await send('traveler',command('voucher.save',voucherId,0,{tripId,authorizationId:authId,expenseIds:[expenseId],formSchemaVersion:'ouranos.fixture.v1',formData:{certified:true}}));expect(save.status,JSON.stringify(save.body)).toBe(200);const submitted=await send('traveler',command('voucher.submit',voucherId,1,{}));expect(submitted.body.error.code).toBe('VALIDATION_FAILED');const stored=await request('traveler','GET',`/v1/entities/voucher/${voucherId}?organizationId=${org}`);expect(stored.body.entity.data.expenseIds).toEqual([expenseId]);expect(stored.body.entity.status).toBe('draft');const inbox=await request('reviewer','GET',`/v1/entities/approval?organizationId=${org}`);expect(inbox.body.entities.some((row:{data:{entityId?:string}})=>row.data.entityId===voucherId)).toBe(false)});
 it('rejects unintegrated form versions at submission',async()=>{const id=crypto.randomUUID();await send('traveler',command('authorization.save',id,0,{tripId,formSchemaVersion:'partner.pending',formData:{}}));const r=await send('traveler',command('authorization.submit',id,1,{}));expect(r.body.error.code).toBe('VALIDATION_FAILED')});
 it('provides a scoped sync package and audit history',async()=>{const bootstrap=await request('traveler','GET',`/v1/sync/bootstrap?organizationId=${org}`);expect(bootstrap.status,JSON.stringify(bootstrap.body)).toBe(200);expect(bootstrap.body.entities.some((e:any)=>e.id===tripId)).toBe(true);const noAccess=await request('outsider','GET',`/v1/sync/pull?organizationId=${org}`);expect(noAccess.status).toBe(403);const log=await request('traveler','GET',`/v1/trips/${tripId}/audit?organizationId=${org}`);expect(log.body.events.length).toBeGreaterThan(5);expect(log.body.events).toEqual(expect.arrayContaining([expect.objectContaining({action:'receipt.process',entity_id:docId})]))});
});
