'use client';
import {useEffect,useState} from 'react';import {usePlatform} from '@/components/platform/provider';import {Button} from '@/components/ui/button';import {Textarea} from '@/components/ui/textarea';import type {Entity,Command} from '@/packages/contracts';
export default function Review(){const p=usePlatform();const [requests,setRequests]=useState<Entity[]>([]),[selected,setSelected]=useState<Entity|null>(null),[detail,setDetail]=useState<any>(null),[comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){if(!p.client||!p.organizationId)return;try{setRequests((await p.client.list('approval',p.organizationId)).entities);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load reviews')}}
 useEffect(()=>{void refresh()},[p.client,p.organizationId]);
 async function open(entity:Entity){setSelected(entity);setDetail(null);setError('');try{setDetail(await p.client!.revision(entity.id,p.organizationId!))}catch(e){setError(e instanceof Error?e.message:'Unable to load revision')}}
 async function decide(decision:'approved'|'changes_requested'|'rejected'){if(!selected||!detail||!p.client||!p.organizationId)return;setBusy(true);setError('');try{const result=await p.client.command({type:'approval.decide',commandId:crypto.randomUUID(),organizationId:p.organizationId,entityId:selected.id,expectedVersion:selected.version,deviceId:(await p.repository?.db.meta.get('deviceId'))?.value||crypto.randomUUID(),schemaVersion:1,payload:{decision,comment}} as Command);if(!result.ok)throw new Error(result.error.message);setSelected(null);setDetail(null);setComment('');await refresh();await p.engine?.sync()}catch(e){setError(e instanceof Error?e.message:'Decision failed')}finally{setBusy(false)}}
 const current=detail?.steps?.find((s:any)=>s.status==='pending');const canDecide=selected?.status==='in_review'&&current?.assignee_id===p.session?.user.id;
 return <main className="quiet-page"><header className="quiet-header"><a href="/dashboard" className="quiet-brand">Ouranos</a><a href="/dashboard/platform">Workspace</a></header><section className="platform-panel"><h1>Review inbox</h1><p className="platform-muted">Decisions apply to the submitted revision. A connection is required to record a decision.</p>{error&&<p role="alert">{error}</p>}{!selected?<>{requests.map(r=><button className="platform-record review-record" key={r.id} onClick={()=>void open(r)}><strong>{String(r.data.kind)} request</strong><span>{r.status.replaceAll('_',' ')}</span></button>)}{!requests.length&&<p>No requests assigned to you.</p>}</>:<div className="platform-block"><Button variant="ghost" onClick={()=>{setSelected(null);setDetail(null)}}>Back to inbox</Button><h2>Submitted {String(selected.data.kind)}</h2>{detail?<><dl className="revision-fields"><dt>Destination</dt><dd>{detail.revision.snapshot.trip?.data.destination}</dd><dt>Travel dates</dt><dd>{detail.revision.snapshot.trip?.data.departure} — {detail.revision.snapshot.trip?.data.returnDate}</dd><dt>Purpose</dt><dd>{detail.revision.snapshot.trip?.data.purpose}</dd></dl><h3>Form details</h3><pre className="revision-json">{JSON.stringify(detail.revision.snapshot.entity?.data.formData,null,2)}</pre>{detail.revision.snapshot.expenses?.map((e:any)=><p key={e.id}>{e.data.merchant} · {e.data.amountMinor} minor units · {e.data.currency}</p>)}<p className="platform-muted">Your partner’s module can provide a richer form-specific review component. This view displays the saved submission unchanged.</p>{canDecide?<><label htmlFor="decision-comment">Comment</label><Textarea id="decision-comment" value={comment} onChange={e=>setComment(e.target.value)} maxLength={4000}/><div className="platform-actions"><Button disabled={busy} onClick={()=>void decide('approved')}>Approve this revision</Button><Button disabled={busy} variant="outline" onClick={()=>void decide('changes_requested')}>Request changes</Button><Button disabled={busy} variant="outline" onClick={()=>void decide('rejected')}>Reject</Button></div></>:<p>This request is {selected.status.replaceAll('_',' ')}{current?' and awaiting another assigned reviewer':''}.</p>}</>:<p>Loading submission…</p>}</div>}</section></main>
}
