'use client';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowLeft,ArrowRight} from 'lucide-react';
import {usePlatform,SyncIndicator} from '@/components/platform/provider';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function TravelRequest(){
 const router=useRouter();const p=usePlatform();const [destination,setDestination]=useState(''),[departure,setDeparture]=useState(''),[returnDate,setReturnDate]=useState(''),[purpose,setPurpose]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setError('');if(returnDate<departure){setError('Return must follow departure.');return}if(!p.repository){setError('Choose a workspace in Settings.');return}setBusy(true);try{const id=crypto.randomUUID();await p.repository.stage('trip.save',id,{destination:destination.trim(),departure,returnDate,purpose:purpose.trim(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});await p.engine?.sync();router.push(`/dashboard/travel/planning?tripId=${id}`)}catch(e){setError(e instanceof Error?e.message:'Unable to save.');setBusy(false)}}
 return <main className="quiet-page travel-page"><header className="quiet-header"><Link className="quiet-brand" href="/dashboard">Ouranos</Link><Link href="/dashboard/platform">Settings</Link></header><section className="travel-stage"><Link className="back-link" href="/dashboard/travel"><ArrowLeft size={14}/> Travel</Link><h1>Where to?</h1><form className="travel-form" onSubmit={save}><div className="travel-field"><label htmlFor="destination">Destination</label><Input id="destination" placeholder="City, ST" value={destination} onChange={e=>setDestination(e.target.value)} maxLength={120} required/></div><div className="travel-date-fields"><div className="travel-field"><label htmlFor="departure">Departure</label><Input type="date" id="departure" value={departure} onChange={e=>setDeparture(e.target.value)} required/></div><div className="travel-field"><label htmlFor="return">Return</label><Input type="date" id="return" min={departure} value={returnDate} onChange={e=>setReturnDate(e.target.value)} required/></div></div><div className="travel-field"><label htmlFor="purpose">Purpose</label><Input id="purpose" value={purpose} onChange={e=>setPurpose(e.target.value)} maxLength={250} required/></div>{error&&<p role="alert" className="form-error">{error}</p>}<Button type="submit" disabled={busy} className="continue-button">{busy?'Saving…':'Continue'}<ArrowRight size={16}/></Button></form></section><footer className="quiet-footer"><span/><SyncIndicator/></footer></main>;
}
