"use client";
import { useEffect, useState } from "react";
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Bell, CalendarDays, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, FileText, House, Layers3, LogOut, MapPin, Orbit, Plane, Plus, Search, ShieldCheck, Sparkles, Wallet, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from "@/components/ui/sidebar";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from "@/components/ui/table";
import { Toaster, toast } from "sonner";

type Trip={id:string;destination:string;location:string;dates:string;status:string;amount:string;purpose:string};
const samples:Trip[]=[
{id:"TRV-2026-042",destination:"Washington, DC",location:"Pentagon",dates:"Oct 12–15, 2026",status:"Needs attention",amount:"$1,248.00",purpose:"Quarterly program review"},
{id:"TRV-2026-039",destination:"San Diego, CA",location:"Naval Base San Diego",dates:"Oct 20–23, 2026",status:"In review",amount:"$1,862.00",purpose:"Operations planning workshop"},
{id:"TRV-2026-031",destination:"Huntsville, AL",location:"Redstone Arsenal",dates:"Sep 08–10, 2026",status:"Completed",amount:"$986.40",purpose:"Technical coordination meeting"},
];
const statusClass=(s:string)=>s==='Needs attention'?'amber':s==='In review'?'blue':s==='Completed'?'green':'gray';
export default function Workspace({travel=false}:{travel?:boolean}){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [drafts,setDrafts]=useState<Trip[]>([]);const [ready,setReady]=useState(false);
 const [newTrip,setNewTrip]=useState(false);const [step,setStep]=useState(1);const [destination,setDestination]=useState('');const [departure,setDeparture]=useState('');const [returnDate,setReturnDate]=useState('');const [purpose,setPurpose]=useState('');const [formError,setFormError]=useState('');const [selected,setSelected]=useState<Trip|null>(null);const [help,setHelp]=useState(false);const [notifications,setNotifications]=useState(false);
 useEffect(()=>{try{const data=JSON.parse(localStorage.getItem('ouranos-demo-drafts')||'[]');if(Array.isArray(data))setDrafts(data.filter(d=>d&&typeof d.id==='string'&&typeof d.destination==='string'&&typeof d.dates==='string'&&d.status==='Draft'));}catch{}setReady(true)},[]);
 const trips=[...drafts,...samples];
 const filtered=trips.filter(t=>(filter==='all'||(filter==='upcoming'&&['Needs attention','In review'].includes(t.status))||(filter==='draft'&&t.status==='Draft')||(filter==='completed'&&t.status==='Completed'))&&(!travel||`${t.destination} ${t.id} ${t.purpose}`.toLowerCase().includes(query.toLowerCase())));
 const found=['travel','dts','trip','voucher','expense','reimbursement','authorization','flight','receipt'].some(word=>word.includes(query.toLowerCase().trim())||query.toLowerCase().includes(word));
 function startTrip(){setStep(1);setDestination('');setDeparture('');setReturnDate('');setPurpose('');setFormError('');setNewTrip(true)}
 function saveDraft(){const trip:Trip={id:`DRAFT-${Date.now().toString().slice(-6)}`,destination,location:'New travel authorization',dates:`${departure} → ${returnDate}`,status:'Draft',amount:'Not estimated',purpose};try{const updated=[trip,...drafts];localStorage.setItem('ouranos-demo-drafts',JSON.stringify(updated));setDrafts(updated);setNewTrip(false);toast.success('Draft saved in this browser',{description:'Nothing has been sent to DTS.'})}catch{setFormError('Your browser could not save this draft. Enable local storage and try again.')}}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'open_travel_workspace',description:'Navigate to the Ouranos demo travel workspace. Does not create or submit a travel request.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');window.location.assign('/dashboard/travel');return {destination:'/dashboard/travel',status:'navigation_started'}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 return <SidebarProvider style={{'--sidebar-width':'232px'} as React.CSSProperties}><Sidebar className="ouranos-sidebar"><SidebarHeader><a className="brand side-brand" href="/dashboard"><Orbit size={28}/><span>ouranos<span className="brand-dot">.</span></span></a><div className="workspace-label"><div className="workspace-icon"><Layers3 size={16}/></div><div>Personal workspace<small>Ouranos preview</small></div><span className="tiny-tag">DEMO</span></div></SidebarHeader><SidebarContent><div className="nav-label">WORKSPACE</div><SidebarMenu>{[{label:'Overview',href:'/dashboard',icon:House,active:!travel},{label:'Travel',href:'/dashboard/travel',icon:Plane,active:travel}].map(({label,href,icon:Icon,active})=><SidebarMenuItem key={label}><SidebarMenuButton asChild isActive={active} className="nav-link"><a href={href}><Icon/><span>{label}</span>{label==='Travel'&&<span className="nav-mini">DTS</span>}</a></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="nav-expansion"><span/> More workflows.<br/><span className="indented">One connected workspace.</span></div></SidebarContent><SidebarFooter><div className="preview-panel"><div><ShieldCheck size={16}/> Preview environment</div><p>Sample data. DTS is not connected.</p></div><Button variant="ghost" className="help-button" onClick={()=>setHelp(true)}><CircleHelp size={16}/> Help & getting started <ArrowUpRight size={14}/></Button><div className="profile"><span className="avatar">AT</span><div>Alex Taylor<small>Demo traveler</small></div><a href="/" aria-label="Return to login" title="Return to login"><LogOut size={16}/></a></div></SidebarFooter></Sidebar>
 <div className="workspace-main"><header className="app-header"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>Workspace</span><ChevronRight size={13}/><strong>{travel?'Travel':'Overview'}</strong>{travel&&<span className="dts-tag">DTS</span>}</div><div className="header-right"><span className="preview-chip"><span/> Product preview</span><button className="notification-button" aria-label="Notifications" onClick={()=>setNotifications(true)}><Bell size={18}/><i/></button><span className="avatar small">AT</span></div></header>
 <main className="dashboard-content"><div className="page-heading"><div><div className="section-kicker">{travel?'TRAVEL OPERATIONS':'YOUR WORK, CONNECTED'}</div><h1>{travel?'Travel workspace':'Good morning, Alex.'}</h1><p>{travel?'From your first authorization to your final reimbursement.':'A clear view of your work. A simpler way to move it forward.'}</p></div><div className="heading-action">{travel?<Button className="dark-button" onClick={startTrip}><Plus size={16}/> New trip</Button>:<span className="date-label"><CalendarDays size={14}/> Thursday, September 24</span>}</div></div>
 {!travel&&<section className="search-section"><form onSubmit={e=>{e.preventDefault();if(query&&found)window.location.assign('/dashboard/travel')}}><Search size={20}/><Input aria-label="Find a workflow" placeholder="What do you need to do? Try ‘travel’" value={query} onChange={e=>setQuery(e.target.value)}/><span className="search-hint">FIND A WORKFLOW</span>{query&&<button type="button" aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}</form>{query&&<div className="search-results" aria-live="polite">{found?<a href="/dashboard/travel"><span className="icon-tile"><Plane size={21}/></span><div><strong>Travel / DTS</strong><small>Authorizations, vouchers, and trip records</small></div><ArrowRight size={18}/></a>:<div className="no-results">No matching workflow. Travel / DTS is the first available workspace.</div>}</div>}</section>}
 {travel?<section className="travel-banner"><div className="icon-tile"><Plane size={23}/></div><div><strong>Defense Travel System</strong><p>Your travel workflow, brought together in Ouranos.</p></div><span className="connection-label"><span/> Not connected · demo data</span></section>:<section className="workflow-section"><div className="section-title"><h2>Your workflows <span>01</span></h2><span>Built around the work you do</span></div><a className="travel-card" href="/dashboard/travel"><div className="travel-card-main"><div className="travel-card-top"><span className="travel-icon"><Plane size={25}/></span><span className="available-pill"><span/> AVAILABLE IN PREVIEW</span></div><div className="travel-card-copy"><div className="section-kicker">DEFENSE TRAVEL SYSTEM</div><h2>Travel, without the back-and-forth.</h2><p>Plan a trip. Prepare your voucher. Keep every detail in one place.</p></div><span className="travel-cta">Open Travel <ArrowRight size={17}/></span></div><div className="travel-card-side"><div className="mini-step"><span><FileText size={16}/></span><div>Authorize<small>Set your trip in motion</small></div><Check size={14}/></div><div className="mini-step"><span><Plane size={16}/></span><div>Travel<small>Keep the details together</small></div></div><div className="mini-step"><span><Wallet size={16}/></span><div>Reconcile<small>Close the loop on expenses</small></div></div></div></a></section>}
 <section className="metrics"><div><span><Plane size={16}/> Upcoming trips</span><strong>02<small>Scheduled in October</small></strong></div><div><span><Clock3 size={16}/> Needs your attention</span><strong>01<small className="attention-text">One document to review</small></strong></div><div><span><FileText size={16}/> Draft authorizations</span><strong>{String(drafts.length).padStart(2,'0')}<small>Saved in this browser</small></strong></div><div><span><CheckCircle2 size={16}/> Completed trips</span><strong>01<small>All steps complete</small></strong></div></section>
 <div className="work-grid"><section className="trips-panel"><div className="section-title"><h2>{travel?'Your trips':'Recent travel'}</h2>{!travel?<a href="/dashboard/travel">View all trips <ArrowUpRight size={14}/></a>:<span>{trips.length} records</span>}</div>{travel&&<div className="trip-tools"><Tabs value={filter} onValueChange={setFilter}><TabsList variant="line"><TabsTrigger value="all">All trips</TabsTrigger><TabsTrigger value="upcoming">Upcoming</TabsTrigger><TabsTrigger value="draft">Drafts</TabsTrigger><TabsTrigger value="completed">Completed</TabsTrigger></TabsList></Tabs><div className="trip-search"><Search size={15}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a trip" aria-label="Find a trip"/></div></div>}<Table className="trip-table"><TableHeader><TableRow><TableHead>DESTINATION</TableHead><TableHead>TRAVEL DATES</TableHead><TableHead>STATUS</TableHead><TableHead><span className="sr-only">Open trip</span></TableHead></TableRow></TableHeader><TableBody>{(travel?filtered:trips.slice(0,3)).map(trip=><TableRow key={trip.id}><TableCell><button className="destination-button" onClick={()=>setSelected(trip)}><span className="destination-icon"><MapPin size={17}/></span><span><strong>{trip.destination}</strong><small>{trip.id}</small></span></button></TableCell><TableCell className="trip-date">{trip.dates}</TableCell><TableCell><span className={`status-badge ${statusClass(trip.status)}`}><span/>{trip.status}</span></TableCell><TableCell><button className="row-open" aria-label={`Open ${trip.destination} trip`} onClick={()=>setSelected(trip)}><ChevronRight size={16}/></button></TableCell></TableRow>)}</TableBody></Table>{travel&&!filtered.length&&<div className="empty-trips"><FileText size={26}/><h3>{filter==='draft'&&!query?'No drafts yet':'No matching trips'}</h3><p>{filter==='draft'&&!query?'Start a new trip to save your first authorization.':'Try another search or trip filter.'}</p>{filter==='draft'&&!query&&<Button variant="outline" onClick={startTrip}>Start a trip</Button>}</div>}</section><aside className="attention-panel"><div className="section-title"><h2>Next up</h2><span className="count-circle">1</span></div><div className="attention-card"><span className="attention-label"><span/> ACTION NEEDED</span><h3>One detail before<br/>you’re ready.</h3><p>Your Washington trip has an item that needs your review.</p><div className="document-item"><FileText size={18}/><div>Supporting document<small>Washington, DC · Oct 12–15</small></div></div><Button variant="outline" onClick={()=>setSelected(samples[0])}>Review trip <ArrowRight size={15}/></Button></div><div className="small-tip"><Sparkles size={16}/><p>Start with the work.<br/><span>Ouranos keeps the steps connected.</span></p></div></aside></div>
 <footer className="app-footer"><span><Orbit size={14}/> OURANOS <span className="footer-divider">/</span> OPERATIONS, CONNECTED.</span><span>Interactive prototype · sample records</span></footer>
 </main></div>
 <Dialog open={newTrip} onOpenChange={setNewTrip}><DialogContent className="trip-dialog"><DialogHeader><div className="modal-kicker">TRAVEL / DTS · NEW AUTHORIZATION</div><DialogTitle>{step===1?'Where is the work taking you?':'Review your trip details'}</DialogTitle><DialogDescription>{step===1?'Start a draft with the essentials.':'Check the details before saving your local draft.'}</DialogDescription></DialogHeader><div className="step-track"><span className="active">1 <b>Trip details</b></span><div/><span className={step===2?'active':''}>2 <b>Review</b></span></div>{step===1?<form onSubmit={e=>{e.preventDefault();if(returnDate<departure){setFormError('Return date must be on or after your departure.');return;}if(!destination.trim()||!purpose.trim()){setFormError('Enter a destination and purpose.');return;}setFormError('');setStep(2)}}><div className="form-field"><label htmlFor="destination">Destination</label><Input id="destination" placeholder="City or installation" value={destination} onChange={e=>setDestination(e.target.value)} required maxLength={100}/></div><div className="date-fields"><div className="form-field"><label htmlFor="departure">Departure</label><Input id="departure" type="date" value={departure} onChange={e=>setDeparture(e.target.value)} required/></div><div className="form-field"><label htmlFor="return">Return</label><Input id="return" type="date" min={departure} value={returnDate} onChange={e=>setReturnDate(e.target.value)} required/></div></div><div className="form-field"><label htmlFor="purpose">Purpose of travel</label><Input id="purpose" placeholder="What is this trip for?" value={purpose} onChange={e=>setPurpose(e.target.value)} required maxLength={200}/></div>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="modal-footer"><span>Step 1 of 2</span><Button type="submit" className="dark-button">Review details <ArrowRight size={15}/></Button></div></form>:<><dl className="detail-list"><div><dt>Destination</dt><dd>{destination}</dd></div><div><dt>Departure</dt><dd>{departure}</dd></div><div><dt>Return</dt><dd>{returnDate}</dd></div><div><dt>Purpose</dt><dd>{purpose}</dd></div></dl><p className="demo-disclosure">This draft stays in this browser. It is not an approved authorization and will not be submitted to DTS.</p>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="modal-footer"><Button variant="ghost" onClick={()=>setStep(1)}>Back</Button><Button className="dark-button" onClick={saveDraft} disabled={!ready}><Check size={16}/> Save draft</Button></div></>}</DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="trip-dialog"><DialogHeader><div className="modal-kicker">{selected?.id}</div><DialogTitle>{selected?.destination}</DialogTitle><DialogDescription>{selected?.purpose}</DialogDescription></DialogHeader>{selected&&<><span className={`status-badge ${statusClass(selected.status)}`}><span/>{selected.status}</span><dl className="detail-list"><div><dt>Travel dates</dt><dd>{selected.dates}</dd></div><div><dt>Location</dt><dd>{selected.location}</dd></div><div><dt>Estimated expenses</dt><dd>{selected.amount}</dd></div><div><dt>Source</dt><dd>{selected.status==='Draft'?'Local draft':'Sample record'}</dd></div></dl>{selected.status==='Needs attention'&&<div className="detail-attention"><FileText size={20}/><div><strong>Supporting document needs review</strong><p>This sample trip demonstrates how an outstanding item will appear before an authorization is ready.</p></div></div>}<p className="demo-disclosure">DTS is not connected. This preview does not send documents, approvals, or travel requests.</p><Button variant="outline" onClick={()=>{const blob=new Blob([JSON.stringify(selected,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${selected.id}-demo.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success('Demo trip record downloaded')}}><ArrowDownToLine size={16}/> Download demo record</Button></>}</DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>Your first steps in Ouranos</DialogTitle><DialogDescription>A focused workspace for travel.</DialogDescription></DialogHeader><ol className="help-steps"><li><b>1. Open Travel</b><p>Choose the Travel card, sidebar link, or search for “DTS”.</p></li><li><b>2. Start a trip</b><p>Enter a destination, dates, and purpose, then review your draft.</p></li><li><b>3. Pick up where you left off</b><p>Drafts are saved in this browser. Sample trips show the intended review experience.</p></li></ol><p className="demo-disclosure">This is a product prototype. Authentication, DTS integration, receipt processing, approvals, and offline synchronization are not connected.</p></DialogContent></Dialog>
 <Dialog open={notifications} onOpenChange={setNotifications}><DialogContent><DialogHeader><DialogTitle>Notifications</DialogTitle><DialogDescription>Updates from your sample workspace.</DialogDescription></DialogHeader><button className="notification-row" onClick={()=>{setNotifications(false);setSelected(samples[0])}}><FileText size={20}/><div><strong>Washington trip needs your attention</strong><p>Review the supporting document in your trip.</p><small>Sample notification</small></div><ChevronRight size={16}/></button></DialogContent></Dialog><Toaster position="bottom-right"/>
 </SidebarProvider>
}
