'use client';

import {useEffect,useMemo,useRef,useState,useSyncExternalStore,type ReactNode} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {ArrowLeft,ArrowRight,Check,FileText,Plus,Trash2,Upload} from 'lucide-react';
import {z} from 'zod';
import {usePlatform,SyncIndicator} from '@/components/platform/provider';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import type {Command,Entity,PayloadOf} from '@/packages/contracts';
import {planningModuleSchema,PLANNING_SCHEMA_VERSION,parseAmountMinor,travelCategories,type PlannedExpense} from '@/packages/contracts/planning-module';
import {voucherModuleSchema,VOUCHER_MODULE_SCHEMA_VERSION} from '@/packages/contracts/voucher-module';
import {approvedTravel,reconcileStoredExpenses,type ApprovedRevision,type Resolution,type Reconciliation} from '@/packages/domain/voucher-adapter';
import type {LocalRecord} from '@/packages/offline/database';

type Platform=ReturnType<typeof usePlatform>;
type Module='planning'|'vouchers';
type Category=typeof travelCategories[number];
const categoryLabels:Record<Category,string>={airfare:'Airfare',lodging:'Lodging',rental_car:'Rental car',fuel:'Fuel',meals:'Meals & incidentals',parking:'Parking',ground_transport:'Ground transport',baggage:'Baggage',other:'Other'};
const money=(minor:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(minor/100);
const dollars=(minor:unknown)=>typeof minor==='number'?(minor/100).toFixed(2):'';
const text=(value:unknown)=>typeof value==='string'?value:'';
const label=(value:string)=>value.replaceAll('_',' ');
const record=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const displayDate=(value:unknown)=>text(value)?new Date(`${value}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';
const editable=(row?:LocalRecord)=>!row||['draft','changes_requested'].includes(row.server?.status||row.local.status);
const recent=(rows:LocalRecord[],kind:string,tripId:string)=>rows.filter(r=>r.kind===kind&&r.local.tripId===tripId).sort((a,b)=>b.local.updatedAt.localeCompare(a.local.updatedAt))[0];
function message(error:unknown){return error instanceof z.ZodError?error.issues.map(i=>i.message).filter((v,i,a)=>a.indexOf(v)===i).join(' '):error instanceof Error?error.message:'Unable to complete this action. Please try again.'}
function useFeedback(){
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');const active=useRef(false);
 async function run(name:string,fn:()=>Promise<string|void>){if(active.current)return;active.current=true;setBusy(name);setError('');setNotice('');try{const result=await fn();if(result)setNotice(result)}catch(e){setError(message(e))}finally{active.current=false;setBusy('')}}
 return {busy,error,notice,run,setError,setNotice};
}
function useUnsaved(dirty:boolean){useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])}
function Feedback({error,notice}:{error:string;notice:string}){return <>{error&&<p className="cw-feedback cw-error" role="alert">{error}</p>}{notice&&<p className="cw-feedback cw-notice" role="status">{notice}</p>}</>}
function Field({label:caption,children,className=''}:{label:string;children:ReactNode;className?:string}){return <label className={`cw-field ${className}`}><span>{caption}</span>{children}</label>}
function Categories(){return travelCategories.map(c=><option key={c} value={c}>{categoryLabels[c]}</option>)}
function Status({value}:{value:string}){return <span className={`cw-status cw-status-${value}`}>{label(value)}</span>}
async function deviceId(p:Platform){const db=p.repository!.db;return db.transaction('rw',db.meta,async()=>{const saved=(await db.meta.get('deviceId'))?.value;if(saved)return saved;const id=crypto.randomUUID();await db.meta.put({key:'deviceId',value:id});return id})}
async function readyToSubmit(p:Platform,tripId:string){
 if(!p.client||!p.engine||!p.repository||!p.organizationId)throw new Error('Connect your workspace before submitting for review.');
 await p.engine.sync();
 const pending=await p.repository.db.outbox.toArray();
 if(pending.some(q=>q.command.entityId===tripId||record(q.command.payload).tripId===tripId))throw new Error('Some trip changes are still on this device. Sync them before submitting. Check workspace settings if a change needs attention.');
}
async function onlineCommand(p:Platform,type:'authorization.submit'|'voucher.submit'|'document.confirm'|'document.reprocess',id:string){
 if(!p.client||!p.repository||!p.engine||!p.organizationId)throw new Error('A connection to your workspace is required.');
 const kind=type.startsWith('authorization')?'authorization':type.startsWith('voucher')?'voucher':'document';
 if(await p.repository.db.outbox.where('entityKey').equals(`${kind}:${id}`).count())throw new Error('Sync this record’s pending changes first.');
 const {entity}=await p.client.get(kind,id,p.organizationId);
 // A response can be lost after a successful submission. Reading its current
 // state avoids saving over it or submitting the same revision twice.
 if((type.endsWith('.submit')&&['in_review','approved'].includes(entity.status))||(type==='document.confirm'&&entity.status==='ready')){await p.engine.merge(entity);return entity}
 const key=`online:${type}:${id}:${entity.version}`;let saved=(await p.repository.db.meta.get(key))?.value;
 if(!saved){const command:Command={type,commandId:crypto.randomUUID(),organizationId:p.organizationId,deviceId:await deviceId(p),entityId:id,expectedVersion:entity.version,schemaVersion:1,payload:{}};saved=JSON.stringify(command);await p.repository.db.meta.put({key,value:saved})}
 const result=await p.client.command(JSON.parse(saved));if(!result.ok)throw new Error(result.error.message);
 await p.engine.merge(result.entity);await p.engine.sync();return result.entity;
}
async function stageMessage(p:Platform,id:string,kind:string){await p.engine?.sync();const pending=await p.repository!.db.outbox.where('entityKey').equals(`${kind}:${id}`).count();return pending?'Saved on this device. It will sync when connected.':'Saved to Ouranos.'}

function subscribeLocation(callback:()=>void){window.addEventListener('popstate',callback);return()=>window.removeEventListener('popstate',callback)}
const currentTripId=()=>new URLSearchParams(window.location.search).get('tripId')||'';
export function ConnectedWorkflow({module}:{module:Module}){
 const p=usePlatform();const tripId=useSyncExternalStore(subscribeLocation,currentTripId,()=>null);
 return <main className="quiet-page cw-page"><header className="quiet-header"><a href="/dashboard" className="quiet-brand">Ouranos</a><a className="cw-workspace-link" href="/dashboard/platform">Workspace</a></header>
  {tripId===null||!p.repository||p.repository.organizationId!==p.organizationId?<section className="cw-shell"><p className="cw-muted">{p.loading||p.organizationId?'Opening your workspace…':'Choose an organization in workspace settings to continue.'}</p></section>:<WorkflowLoader key={`${p.repository.db.name}:${tripId}:${module}`} module={module} tripId={tripId}/>}
  <footer className="cw-footer"><span>Travel / DTS</span><SyncIndicator/></footer>
 </main>;
}
function WorkflowLoader({module,tripId}:{module:Module;tripId:string}){
 const p=usePlatform();const rows=useLiveQuery<LocalRecord[]>(()=>p.repository!.db.entities.toArray(),[p.repository]);const [hydrated,setHydrated]=useState(!p.configured);
 useEffect(()=>{let active=true;if(p.engine)void p.engine.sync().then(()=>{if(active)setHydrated(true)});return()=>{active=false}},[p.engine]);
 if(!rows||!hydrated)return <section className="cw-shell"><p className="cw-muted" role="status">Loading your saved travel…</p></section>;
 const trip=rows.find(r=>r.kind==='trip'&&r.id===tripId)?.local;
 if(!trip)return <section className="cw-shell"><a href="/dashboard" className="back-link"><ArrowLeft size={14}/> Back</a><h1>{module==='planning'?'Plan your travel.':'Prepare your voucher.'}</h1><p className="cw-muted">{tripId?'This trip is not available in this workspace.':'Choose a saved trip to continue.'}</p><div className="cw-trip-list">{rows.filter(r=>r.kind==='trip').map(r=><a key={r.id} href={`/dashboard/travel/${module}?tripId=${r.id}`}><div><strong>{text(r.local.data.destination)}</strong><span>{displayDate(r.local.data.departure)} — {displayDate(r.local.data.returnDate)}</span></div><ArrowRight size={18}/></a>)}</div><Button asChild><a href="/dashboard/travel">Start a trip <Plus size={16}/></a></Button>{p.sync.message&&<p className="cw-muted">{p.sync.message}</p>}</section>;
 return <section className="cw-shell"><a href="/dashboard/platform" className="back-link"><ArrowLeft size={14}/> Your trips</a><nav className="cw-steps" aria-label="Travel process"><a aria-current={module==='planning'?'step':undefined} href={`/dashboard/travel/planning?tripId=${trip.id}`}><span>01</span> Travel plan</a><span className="cw-step-rule"/><a aria-current={module==='vouchers'?'step':undefined} href={`/dashboard/travel/vouchers?tripId=${trip.id}`}><span>02</span> Expenses & voucher</a></nav>
 <div className="cw-heading"><div><p className="cw-eyebrow">{text(trip.data.destination)}</p><h1>{module==='planning'?'Make a plan.':'Bring it together.'}</h1><p className="cw-muted">{displayDate(trip.data.departure)} — {displayDate(trip.data.returnDate)}</p></div></div>
 {module==='planning'?<PlanningForm trip={trip} rows={rows}/>:<VoucherGate trip={trip} rows={rows}/>}</section>;
}

type BudgetDraft={id:string;category:Category;description:string;amount:string;merchant:string;payment:''|'gtcc'|'personal';date:string;startDate:string;endDate:string};
function budgetDraft(item?:PlannedExpense):BudgetDraft{return {id:item?.id||crypto.randomUUID(),category:item?.category||'airfare',description:item?.description||'',amount:item?dollars(item.authorizedAmountMinor):'',merchant:item?.merchant||'',payment:item?.expectedPaymentMethod||'',date:item?.date||'',startDate:item?.startDate||'',endDate:item?.endDate||''}}
function PlanningForm({trip,rows}:{trip:Entity;rows:LocalRecord[]}){
 const p=usePlatform(),feedback=useFeedback();
 const [initial]=useState(()=>recent(rows,'authorization',trip.id));const [id]=useState(()=>initial?.id||crypto.randomUUID());
 const parsed=planningModuleSchema.safeParse(initial?.local.data.formData);
 const [traveler,setTraveler]=useState(()=>parsed.success?parsed.data.traveler:''),[origin,setOrigin]=useState(()=>parsed.success?parsed.data.origin:'');
 const [items,setItems]=useState<BudgetDraft[]>(()=>parsed.success?parsed.data.approvedExpenseItems.map(budgetDraft):[budgetDraft()]);
 const [dirty,setDirty]=useState(false);const baselineVersion=useRef(initial?.local.version||0);useUnsaved(dirty);
 const row=rows.find(r=>r.id===id&&r.kind==='authorization'),locked=!editable(row);
 const unsupported=Boolean(initial&&initial.local.data.formSchemaVersion!==PLANNING_SCHEMA_VERSION);
 const total=items.reduce((sum,item)=>{try{return sum+parseAmountMinor(item.amount)}catch{return sum}},0);
 const status=row?.server?.status||row?.local.status||'draft';
 function updateItem(index:number,patch:Partial<BudgetDraft>){setItems(current=>current.map((item,i)=>i===index?{...item,...patch}:item));setDirty(true)}
 async function save(){
  const current=await p.repository!.db.entities.get(`authorization:${id}`);if(!editable(current))throw new Error('This plan has already been submitted. Refresh to see its review status.');
  if((current?.local.version||0)!==baselineVersion.current)throw new Error('This plan changed in another session. Your edits are still here; reload to review the newer version before saving.');
  const form=planningModuleSchema.parse({traveler,origin,currency:'USD',approvedExpenseItems:items.map(item=>({id:item.id,category:item.category,description:item.description,authorizedAmountMinor:parseAmountMinor(item.amount),...(item.merchant?{merchant:item.merchant}:{}),...(item.payment?{expectedPaymentMethod:item.payment}:{}),...(item.date?{date:item.date}:{}),...(item.startDate||item.endDate?{startDate:item.startDate,endDate:item.endDate}:{} )}))});
  await p.repository!.stage('authorization.save',id,{tripId:trip.id,formSchemaVersion:PLANNING_SCHEMA_VERSION,formData:form});baselineVersion.current=(await p.repository!.db.entities.get(`authorization:${id}`))!.local.version;setDirty(false);return stageMessage(p,id,'authorization');
 }
 async function submit(){
  if(dirty||!row)await save();await readyToSubmit(p,trip.id);const result=await onlineCommand(p,'authorization.submit',id);setDirty(false);return result.status==='approved'?'This plan is approved.':'Sent to your configured review route.';
 }
 if(unsupported)return <div className="cw-card"><h2>A different planning form is attached.</h2><p className="cw-muted">This saved authorization uses an older or partner form. Its data has been preserved.</p><a href="/dashboard/platform">Return to workspace</a></div>;
 return <><div className="cw-section-heading"><h2>Travel details</h2><Status value={status}/></div>
 {locked&&<div className="cw-banner"><Check size={18}/><div><strong>{status==='approved'?'Your plan is approved.':status==='in_review'?'Your plan is with your reviewers.':'This revision is closed.'}</strong><p>{status==='approved'?'Its approved budget will carry into your voucher.':'Submitted details are preserved with this revision.'}</p></div>{status==='approved'&&<a href={`/dashboard/travel/vouchers?tripId=${trip.id}`}>Open voucher <ArrowRight size={16}/></a>}</div>}
 <form onSubmit={e=>{e.preventDefault();void feedback.run('save',save)}}><fieldset disabled={locked||!!feedback.busy} className="cw-fieldset"><div className="cw-card cw-grid"><Field label="Traveler name"><Input value={traveler} onChange={e=>{setTraveler(e.target.value);setDirty(true)}} autoComplete="name" maxLength={200} required/></Field><Field label="Starting location"><Input value={origin} onChange={e=>{setOrigin(e.target.value);setDirty(true)}} placeholder="City or installation" maxLength={120} required/></Field><div className="cw-span-full cw-purpose"><span>Purpose</span><p>{text(trip.data.purpose)}</p></div></div>
 <div className="cw-section-heading"><div><h2>Planned expenses</h2><p className="cw-muted">Build the budget your reviewers will approve.</p></div><span className="cw-budget-total">{money(total)} <small>USD</small></span></div>
 <div className="cw-budget-list">{items.map((item,index)=><article className="cw-card cw-budget-item" key={item.id}><div className="cw-item-heading"><span>Expense {String(index+1).padStart(2,'0')}</span>{!locked&&items.length>1&&<button className="cw-icon-button" type="button" aria-label={`Remove planned expense ${index+1}`} onClick={()=>{setItems(current=>current.filter(x=>x.id!==item.id));setDirty(true)}}><Trash2 size={16}/></button>}</div><div className="cw-grid"><Field label="Category"><select value={item.category} onChange={e=>updateItem(index,{category:e.target.value as Category})}><Categories/></select></Field><Field label="Planned amount · USD"><Input value={item.amount} onChange={e=>updateItem(index,{amount:e.target.value})} placeholder="0.00" inputMode="decimal" required/></Field><Field label="Description" className="cw-span-full"><Input value={item.description} onChange={e=>updateItem(index,{description:e.target.value})} placeholder="For example, return flight to home station" maxLength={300} required/></Field><Field label="Merchant · optional"><Input value={item.merchant} onChange={e=>updateItem(index,{merchant:e.target.value})} maxLength={200}/></Field><Field label="Expected payment"><select value={item.payment} onChange={e=>updateItem(index,{payment:e.target.value as BudgetDraft['payment']})}><option value="">No preference</option><option value="gtcc">GTCC</option><option value="personal">Personal</option></select></Field>{item.category==='lodging'?<><Field label="Check-in · optional"><Input type="date" min={text(trip.data.departure)} max={text(trip.data.returnDate)} value={item.startDate} onChange={e=>updateItem(index,{startDate:e.target.value})}/></Field><Field label="Check-out · optional"><Input type="date" min={item.startDate||text(trip.data.departure)} max={text(trip.data.returnDate)} value={item.endDate} onChange={e=>updateItem(index,{endDate:e.target.value})}/></Field></>:<Field label="Expense date · optional"><Input type="date" min={text(trip.data.departure)} max={text(trip.data.returnDate)} value={item.date} onChange={e=>updateItem(index,{date:e.target.value})}/></Field>}</div></article>)}</div>
 {!locked&&<Button type="button" variant="outline" className="cw-add-button" onClick={()=>{setItems(current=>[...current,budgetDraft()]);setDirty(true)}} disabled={items.length>=100}><Plus size={16}/> Add planned expense</Button>}</fieldset>
 <Feedback error={feedback.error} notice={feedback.notice}/>{!locked&&<div className="cw-action-bar"><div><p>Save as you go.</p><span>Submission sends this revision to your organization’s reviewers.</span></div><div className="cw-actions"><Button variant="outline" type="submit" disabled={!!feedback.busy}>{feedback.busy==='save'?'Saving…':'Save draft'}</Button><Button type="button" disabled={!!feedback.busy||!p.client} onClick={()=>void feedback.run('submit',submit)}>{feedback.busy==='submit'?'Submitting…':'Submit for review'}<ArrowRight size={16}/></Button></div></div>}</form>
 {status==='in_review'&&<p className="cw-muted cw-end-note">Your workspace will update when a reviewer records a decision.</p>}</>;
}

function VoucherGate({trip,rows}:{trip:Entity;rows:LocalRecord[]}){
 const auth=rows.filter(r=>r.kind==='authorization'&&r.local.tripId===trip.id&&r.server?.status==='approved').sort((a,b)=>b.server!.updatedAt.localeCompare(a.server!.updatedAt))[0];
 if(!auth)return <div className="cw-card cw-empty"><FileText size={28}/><h2>Start with an approved plan.</h2><p className="cw-muted">Your voucher will use the exact travel details and budget your reviewers approved.</p><Button asChild><a href={`/dashboard/travel/planning?tripId=${trip.id}`}>Open travel plan <ArrowRight size={16}/></a></Button></div>;
 return <ApprovedVoucher key={`${auth.id}:${auth.server!.version}`} authorizationId={auth.id} trip={trip} rows={rows}/>;
}
function ApprovedVoucher({authorizationId,trip,rows}:{authorizationId:string;trip:Entity;rows:LocalRecord[]}){
 const p=usePlatform();const [revision,setRevision]=useState<ApprovedRevision|null>(null),[error,setError]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;if(!p.client||!p.organizationId)return;void p.client.approvedAuthorization(authorizationId,p.organizationId).then(result=>{approvedTravel(result.revision);if(active)setRevision(result.revision)}).catch(e=>{if(active)setError(message(e))});return()=>{active=false}},[authorizationId,p.client,p.organizationId,reload]);
 if(!revision)return <div className="cw-card"><p className={error?'cw-error':'cw-muted'} role={error?'alert':'status'}>{error||'Loading your approved travel plan…'}</p>{error&&<Button variant="outline" onClick={()=>{setError('');setReload(n=>n+1)}}>Try again</Button>}</div>;
 return <VoucherForm key={revision.id} trip={trip} rows={rows} revision={revision}/>;
}

type ExpenseDraft={id:string;version:number;authorizationItemId:string;merchant:string;date:string;amount:string;category:Category;paymentMethod:'gtcc'|'personal';description:string;documentIds:string[];startDate:string;endDate:string};
function expenseDraft(entity:Entity|undefined,first:PlannedExpense,trip:Entity):ExpenseDraft{return {id:entity?.id||crypto.randomUUID(),version:entity?.version||0,authorizationItemId:text(entity?.data.authorizationItemId)||first.id,merchant:text(entity?.data.merchant)||first.merchant||'',date:text(entity?.data.incurredOn)||first.date||text(trip.data.departure),amount:entity?dollars(entity.data.amountMinor):'',category:(entity?.data.category==='transport'?'ground_transport':entity?.data.category||first.category) as Category,paymentMethod:(entity?.data.paymentMethod||first.expectedPaymentMethod||'gtcc') as 'gtcc'|'personal',description:text(entity?.data.description),documentIds:Array.isArray(entity?.data.documentIds)?entity.data.documentIds as string[]:[],startDate:text(entity?.data.serviceStartDate)||first.startDate||'',endDate:text(entity?.data.serviceEndDate)||first.endDate||''}}
function VoucherForm({trip,rows,revision}:{trip:Entity;rows:LocalRecord[];revision:ApprovedRevision}){
 const p=usePlatform(),feedback=useFeedback();const approved=planningModuleSchema.parse(revision.snapshot.entity.data.formData);
 const [initial]=useState(()=>recent(rows,'voucher',trip.id));const [id]=useState(()=>initial?.id||crypto.randomUUID());const baselineVersion=useRef(initial?.local.version||0);const form=record(initial?.local.data.formData);
 const row=rows.find(r=>r.kind==='voucher'&&r.id===id),locked=!editable(row),status=row?.server?.status||row?.local.status||'draft';
 const expenses=rows.filter(r=>r.kind==='expense'&&r.local.tripId===trip.id).map(r=>r.local),documents=rows.filter(r=>r.kind==='document'&&r.local.tripId===trip.id).map(r=>r.local);
 const [included,setIncluded]=useState<string[]>(()=>Array.isArray(initial?.local.data.expenseIds)?initial.local.data.expenseIds as string[]:expenses.map(e=>e.id));
 const [resolutions,setResolutions]=useState<Record<string,Resolution>>(()=>record(form.resolutions) as Record<string,Resolution>),[certified,setCertified]=useState(form.certified===true),[intakeComplete,setIntakeComplete]=useState(form.intakeComplete===true),[dirty,setDirty]=useState(false);
 const [editor,setEditor]=useState<ExpenseDraft|null>(null),[reviewReceipt,setReviewReceipt]=useState<string|null>(null);
 useUnsaved(dirty||editor!==null);
 const selected=expenses.filter(e=>included.includes(e.id));
 const reconciliation=useMemo(()=>reconcileStoredExpenses(revision,selected,documents,resolutions),[revision,selected,documents,resolutions]);
 const changed=()=>{setDirty(true);setCertified(false)};
 const unsupported=Boolean(initial&&initial.local.data.formSchemaVersion!==VOUCHER_MODULE_SCHEMA_VERSION);
 function editExpense(entity?:Entity){setEditor(expenseDraft(entity,approved.approvedExpenseItems[0],revision.snapshot.trip));feedback.setError('')}
 async function saveExpense(){
  if(!editor)return;const current=await p.repository!.db.entities.get(`voucher:${id}`);if(!editable(current))throw new Error('This voucher has already been submitted.');
  const currentExpense=await p.repository!.db.entities.get(`expense:${editor.id}`);if((currentExpense?.local.version||0)!==editor.version)throw new Error('This expense changed in another session. Cancel this edit and reopen its current details before saving.');
  const payload:PayloadOf<'expense.save'>={tripId:trip.id,merchant:editor.merchant,incurredOn:editor.date,amountMinor:parseAmountMinor(editor.amount),currency:'USD',category:editor.category,paymentMethod:editor.paymentMethod,authorizationItemId:editor.authorizationItemId,description:editor.description,documentIds:editor.documentIds,...(editor.startDate?{serviceStartDate:editor.startDate}:{}),...(editor.endDate?{serviceEndDate:editor.endDate}:{})};
  await p.repository!.stage('expense.save',editor.id,payload);setIncluded(current=>current.includes(editor.id)?current:[...current,editor.id]);
  setResolutions(current=>Object.fromEntries(Object.entries(current).filter(([key])=>!key.startsWith(`${editor.id}:`)&&key!==`auth:${editor.authorizationItemId}:not_used`)));setEditor(null);changed();return stageMessage(p,editor.id,'expense');
 }
 async function payloadForSave(requireComplete:boolean){
  if(editor)throw new Error('Save or cancel the open expense before saving your voucher.');
  const stored=await p.repository!.db.entities.toArray();const currentExpenses=stored.filter(r=>r.kind==='expense'&&r.local.tripId===trip.id&&included.includes(r.id)).map(r=>r.local);const currentDocuments=stored.filter(r=>r.kind==='document'&&r.local.tripId===trip.id).map(r=>r.local);
  const check=reconcileStoredExpenses(revision,currentExpenses,currentDocuments,resolutions);
  const formData={tripId:trip.id,authorizationId:revision.snapshot.entity.id,currency:'USD',certified,intakeComplete,expenseItems:currentExpenses.map(e=>({expenseId:e.id,authorizationItemId:e.data.authorizationItemId,amountMinor:e.data.amountMinor,currency:e.data.currency,documentIds:e.data.documentIds||[]})),reconciliation:{totalAmountMinor:currentExpenses.reduce((sum,e)=>sum+Number(e.data.amountMinor),0),unresolvedIssueIds:check.issues.map(i=>i.id)},resolutions};
  if(requireComplete){if(!intakeComplete)throw new Error('Confirm that you have accounted for all trip expenses.');if(!certified)throw new Error('Certify the expense details before submitting.');if(!check.ready)throw new Error('Resolve the items listed below before submitting your voucher.');voucherModuleSchema.parse(formData)}
  return {tripId:trip.id,authorizationId:revision.snapshot.entity.id,expenseIds:currentExpenses.map(e=>e.id),formSchemaVersion:VOUCHER_MODULE_SCHEMA_VERSION,formData};
 }
 async function save(requireComplete=false){
  const current=await p.repository!.db.entities.get(`voucher:${id}`);if(!editable(current))throw new Error('This voucher has already been submitted. Refresh to view its status.');
  if((current?.local.version||0)!==baselineVersion.current)throw new Error('This voucher changed in another session. Reload to review the newer revision before saving.');
  const payload=await payloadForSave(requireComplete);if(!payload.expenseIds.length)throw new Error('Add at least one expense to your voucher.');await p.repository!.stage('voucher.save',id,payload);baselineVersion.current=(await p.repository!.db.entities.get(`voucher:${id}`))!.local.version;setDirty(false);return stageMessage(p,id,'voucher');
 }
 async function submit(){
  await readyToSubmit(p,trip.id);
  // Save the current reconciled references only while the record is editable.
  // If a previous response was lost, recover its accepted submission instead.
  const current=await p.repository!.db.entities.get(`voucher:${id}`);
  if(!editable(current)){const result=await onlineCommand(p,'voucher.submit',id);return result.status==='approved'?'Your voucher is approved.':'Your voucher is already with your reviewers.'}
  await save(true);await readyToSubmit(p,trip.id);await onlineCommand(p,'voucher.submit',id);setDirty(false);return 'Voucher submitted to your configured review route.';
 }
 async function capture(files:File[]){for(const file of files)await p.repository!.captureReceipt(trip.id,file);await p.engine?.sync();changed();return 'Receipts saved. Their processing status appears below.'}
 function resolve(issue:Reconciliation['issues'][number],resolution:Resolution){setResolutions(current=>({...current,[issue.id]:{...resolution,at:new Date().toISOString()}}));changed()}
 if(unsupported)return <div className="cw-card"><h2>A different voucher form is attached.</h2><p className="cw-muted">Its data has been preserved. Return to workspace to review the existing record.</p><a href="/dashboard/platform">Workspace</a></div>;
 return <>
 <div className="cw-approved-summary"><div><span className="cw-eyebrow">APPROVED TRAVEL PLAN</span><strong>{approved.traveler}</strong><p>{approved.origin} <ArrowRight size={13}/> {text(revision.snapshot.trip.data.destination)}</p></div><div><span className="cw-muted">Approved budget</span><strong>{money(approved.approvedExpenseItems.reduce((sum,e)=>sum+e.authorizedAmountMinor,0))}</strong><span className="cw-fingerprint" title={revision.sha256}>Revision {revision.id.slice(0,8)}</span></div></div>
 <div className="cw-section-heading"><div><h2>Your expenses</h2><p className="cw-muted">Match each actual expense to the approved budget.</p></div><Status value={status}/></div>
 {locked&&<div className="cw-banner"><Check size={18}/><div><strong>{status==='approved'?'Your voucher is approved.':'This voucher revision is submitted.'}</strong><p>Its expenses and receipt references are preserved for review. DTS delivery is separate.</p></div></div>}
 <div className="cw-expenses">{expenses.map(expense=><article id={`expense-${expense.id}`} className={`cw-expense-row ${included.includes(expense.id)?'':'cw-excluded'}`} key={expense.id}><label className="cw-check"><input type="checkbox" checked={included.includes(expense.id)} disabled={locked||!!feedback.busy} onChange={e=>{setIncluded(current=>e.target.checked?[...current,expense.id]:current.filter(x=>x!==expense.id));changed()}}/><span className="sr-only">Include {text(expense.data.merchant)} in this voucher</span></label><div className="cw-expense-info"><strong>{text(expense.data.merchant)}</strong><span>{label(text(expense.data.category))} · {displayDate(expense.data.incurredOn)} · {expense.data.paymentMethod==='personal'?'Personal':'GTCC'}</span><small>{(expense.data.documentIds as string[]||[]).length} receipt{(expense.data.documentIds as string[]||[]).length===1?'':'s'}{!included.includes(expense.id)?' · Excluded from this voucher':''}</small></div><strong className="cw-expense-amount">{money(Number(expense.data.amountMinor))}</strong>{!locked&&<Button variant="ghost" disabled={!!feedback.busy} onClick={()=>editExpense(expense)}>Edit</Button>}</article>)}</div>
 {!locked&&!editor&&<Button variant="outline" className="cw-add-button" onClick={()=>editExpense()} disabled={!!feedback.busy}><Plus size={16}/> Add expense</Button>}
 {editor&&!locked&&<form id="cw-expense-editor" className="cw-card cw-expense-editor" onSubmit={e=>{e.preventDefault();void feedback.run('expense',saveExpense)}}><div className="cw-section-heading"><h3>{expenses.some(e=>e.id===editor.id)?'Edit expense':'New expense'}</h3></div><fieldset className="cw-fieldset cw-grid" disabled={!!feedback.busy}>
 <Field label="Approved budget item" className="cw-span-full"><select required value={editor.authorizationItemId} onChange={e=>{const item=approved.approvedExpenseItems.find(i=>i.id===e.target.value)!;setEditor({...editor,authorizationItemId:item.id,category:item.category,paymentMethod:item.expectedPaymentMethod||editor.paymentMethod,startDate:item.startDate||'',endDate:item.endDate||''})}}><option value="" disabled>Choose an approved item</option>{approved.approvedExpenseItems.map(item=><option key={item.id} value={item.id}>{item.description} · {money(item.authorizedAmountMinor)}</option>)}</select></Field>
 <Field label="Merchant"><Input value={editor.merchant} onChange={e=>setEditor({...editor,merchant:e.target.value})} maxLength={200} required/></Field><Field label="Amount · USD"><Input value={editor.amount} onChange={e=>setEditor({...editor,amount:e.target.value})} inputMode="decimal" placeholder="0.00" required/></Field><Field label="Expense date"><Input type="date" value={editor.date} onChange={e=>setEditor({...editor,date:e.target.value})} required/></Field><Field label="Payment method"><select required value={editor.paymentMethod} onChange={e=>setEditor({...editor,paymentMethod:e.target.value as ExpenseDraft['paymentMethod']})}><option value="" disabled>Choose payment method</option><option value="gtcc">GTCC</option><option value="personal">Personal</option></select></Field><Field label="Category"><select required value={editor.category} onChange={e=>setEditor({...editor,category:e.target.value as Category})}><option value="" disabled>Choose category</option><Categories/></select></Field><Field label="Description · optional"><Input value={editor.description} onChange={e=>setEditor({...editor,description:e.target.value})} maxLength={2000}/></Field>
 {editor.category==='lodging'&&<><Field label="Check-in"><Input type="date" value={editor.startDate} onChange={e=>setEditor({...editor,startDate:e.target.value})}/></Field><Field label="Check-out"><Input type="date" min={editor.startDate} value={editor.endDate} onChange={e=>setEditor({...editor,endDate:e.target.value})}/></Field></>}
 <div className="cw-span-full cw-attach"><span>Attach receipts</span>{documents.length?documents.map(doc=><label className="cw-check" key={doc.id}><input type="checkbox" checked={editor.documentIds.includes(doc.id)} onChange={e=>setEditor({...editor,documentIds:e.target.checked?[...editor.documentIds,doc.id]:editor.documentIds.filter(id=>id!==doc.id)})}/><span>{text(doc.data.filename)} <small>{label(doc.status)}</small></span></label>):<p className="cw-muted">Save this expense, then add a receipt below and attach it here.</p>}</div>
 </fieldset><div className="cw-actions cw-editor-actions"><Button type="button" variant="ghost" disabled={!!feedback.busy} onClick={()=>setEditor(null)}>Cancel</Button><Button type="submit" disabled={!!feedback.busy}>{feedback.busy==='expense'?'Saving…':'Save expense'}</Button></div></form>}
 <div className="cw-section-heading"><div><h2>Receipts</h2><p className="cw-muted">Upload, review the extracted details, then confirm.</p></div>{!locked&&<label className={`cw-upload-button ${feedback.busy?'is-disabled':''}`}><Upload size={15}/> Add receipt<input type="file" accept="image/jpeg,image/png,application/pdf" multiple disabled={!!feedback.busy} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length)void feedback.run('receipt',()=>capture(files))}}/></label>}</div>
 <div className="cw-card cw-receipt-list">{documents.length?documents.map(doc=><div className="cw-receipt" key={doc.id}><FileText size={19}/><div><strong>{text(doc.data.filename)}</strong><span>{receiptStatus(doc.status)}</span></div>{['needs_review','ready'].includes(doc.status)&&<Button variant="ghost" onClick={()=>setReviewReceipt(reviewReceipt===doc.id?null:doc.id)}>{reviewReceipt===doc.id?'Close':'Review'}</Button>}{!locked&&['failed','awaiting_provider'].includes(doc.status)&&<Button variant="ghost" disabled={!!feedback.busy} onClick={()=>void feedback.run('retry',async()=>{await onlineCommand(p,'document.reprocess',doc.id);return 'Receipt queued for processing.'})}>Retry</Button>}</div>):<p className="cw-muted">No receipts yet. JPEG, PNG, or PDF, up to 20 MB each.</p>}</div>
 {reviewReceipt&&<ReceiptReview key={reviewReceipt} id={reviewReceipt} document={documents.find(d=>d.id===reviewReceipt)!} locked={locked} onConfirmed={()=>{setReviewReceipt(null);changed()}} onUseDetails={(documentId,fields)=>{if(fields.currency&&fields.currency!=='USD'){feedback.setError('This voucher supports USD. Review the receipt currency before adding an expense.');return}const draft=expenseDraft(undefined,approved.approvedExpenseItems[0],revision.snapshot.trip);setEditor({...draft,authorizationItemId:'',merchant:fields.merchant||'',date:/^\d{4}-\d{2}-\d{2}$/.test(fields.date||'')?fields.date:'',amount:fields.amount||'',category:(travelCategories.includes(fields.category as Category)?fields.category:'') as Category,paymentMethod:(['gtcc','personal'].includes(fields.paymentMethod)?fields.paymentMethod:'') as ExpenseDraft['paymentMethod'],documentIds:[documentId],startDate:fields.serviceStartDate||'',endDate:fields.serviceEndDate||''});setReviewReceipt(null);feedback.setNotice('Extracted details added as suggestions. Check each field, choose the approved item, then save the expense.');setTimeout(()=>window.document.getElementById('cw-expense-editor')?.scrollIntoView({block:'center'}),0)}}/>}
 <div className="cw-section-heading"><div><h2>Reconciliation</h2><p className="cw-muted">A final check against the approved plan.</p></div></div>
 <div className="cw-totals"><div><span>Actual expenses</span><strong>{money(Math.round(reconciliation.totals.actual*100))}</strong></div><div><span>GTCC</span><strong>{money(Math.round(reconciliation.totals.gtcc*100))}</strong></div><div><span>Personal</span><strong>{money(Math.round(reconciliation.totals.traveler*100))}</strong></div></div>
 {reconciliation.issues.length?<div className="cw-issues">{reconciliation.issues.map(issue=><Issue key={issue.id} issue={issue} locked={locked} expense={selected.find(e=>e.id===issue.expenseId)} onResolve={resolution=>resolve(issue,resolution)} onEdit={()=>{const expense=expenses.find(e=>e.id===issue.expenseId);if(expense)editExpense(expense)}}/>)}</div>:selected.length>0?<div className="cw-ready"><Check size={18}/> All expenses are accounted for.</div>:<p className="cw-muted">Add an expense to begin reconciliation.</p>}
 {Object.keys(resolutions).length>0&&<details className="cw-resolutions"><summary>{Object.keys(resolutions).length} recorded resolution{Object.keys(resolutions).length===1?'':'s'}</summary>{Object.entries(resolutions).map(([key,value])=><div key={key}><span>{value.type==='not_used'?'Authorized item not used':value.type==='confirmed_date'?`Travel date confirmed: ${value.value}`:value.value}</span>{!locked&&<Button variant="ghost" disabled={!!feedback.busy} onClick={()=>{setResolutions(current=>Object.fromEntries(Object.entries(current).filter(([id])=>id!==key)));changed()}}>Remove</Button>}</div>)}</details>}
 {!locked&&<div className="cw-certification"><label className="cw-check"><input type="checkbox" checked={intakeComplete} disabled={!!feedback.busy} onChange={e=>{setIntakeComplete(e.target.checked);changed()}}/><span>I have accounted for all expenses from this trip.</span></label><label className="cw-check"><input type="checkbox" checked={certified} disabled={!!feedback.busy} onChange={e=>{setCertified(e.target.checked);setDirty(true)}}/><span>I certify that these expenses and supporting documents are accurate.</span></label></div>}
 <Feedback error={feedback.error} notice={feedback.notice}/>{!locked&&<div className="cw-action-bar"><div><p>{reconciliation.ready?'Ready for review.':'Finish the items above.'}</p><span>Your reviewer receives a fixed copy of this voucher.</span></div><div className="cw-actions"><Button variant="outline" disabled={!!feedback.busy||!!editor} onClick={()=>void feedback.run('save',()=>save())}>{feedback.busy==='save'?'Saving…':'Save draft'}</Button><Button disabled={!!feedback.busy||!!editor||!p.client||!certified||!intakeComplete||!reconciliation.ready} onClick={()=>void feedback.run('submit',submit)}>{feedback.busy==='submit'?'Submitting…':'Submit voucher'}<ArrowRight size={16}/></Button></div></div>}
 </>;
}
function receiptStatus(status:string){const labels:Record<string,string>={registered:'Saved · waiting to upload',uploaded:'Queued for processing',processing:'Processing receipt',awaiting_provider:'Waiting for a connected receipt processor',needs_review:'Extracted · ready for your review',ready:'Reviewed and confirmed',quarantined:'File blocked by the security scan',failed:'Processing needs attention'};return labels[status]||label(status)}
function ReceiptReview({id,document:doc,locked,onConfirmed,onUseDetails}:{id:string;document:Entity;locked:boolean;onConfirmed:()=>void;onUseDetails:(id:string,fields:Record<string,string>)=>void}){
 const p=usePlatform(),feedback=useFeedback();const [fields,setFields]=useState<Array<{name:string;value:string;confidence?:number}>|null>(null),[confirmed,setConfirmed]=useState(false),[url,setUrl]=useState('');const setError=feedback.setError;
 useEffect(()=>{let active=true;if(!p.client||!p.organizationId)return;void p.client.extractions(id,p.organizationId).then(result=>{const latest=record(result.runs[0]),extracted=record(latest.result);const values=Array.isArray(extracted.fields)?extracted.fields:[];if(active)setFields(values.map(v=>{const field=record(v);return {name:text(field.name),value:typeof field.value==='string'?field.value:String(field.value??''),confidence:typeof field.confidence==='number'?field.confidence:undefined}}))}).catch(e=>{if(active)setError(message(e))});return()=>{active=false}},[id,p.client,p.organizationId,setError]);
 if(!doc)return null;
 return <section className="cw-card cw-receipt-review"><div className="cw-section-heading"><h3>{text(doc.data.filename)}</h3><Button variant="outline" onClick={()=>void feedback.run('download',async()=>{if(!p.client||!p.organizationId)throw new Error('Connect to view the original receipt.');setUrl((await p.client.download(id,p.organizationId)).url)})}>View original</Button></div>{url&&<p className="cw-muted"><a href={url} target="_blank" rel="noopener noreferrer">Open receipt file <ArrowRight size={13}/></a> · Link expires after one minute.</p>}
 {fields===null?<p className="cw-muted">Loading extracted details…</p>:fields.length?<dl className="cw-extraction">{fields.filter(field=>field.name!=='text').map((field,index)=><div key={`${field.name}:${index}`}><dt>{label(field.name)}</dt><dd>{field.value}{field.confidence!==undefined&&field.confidence<.85&&<small>Check this value carefully</small>}</dd></div>)}</dl>:<p className="cw-muted">No structured fields were returned. Review the original file and enter its details in the expense.</p>}
 {fields?.some(field=>field.name==='text')&&<details className="cw-raw-extraction"><summary>Full extracted text</summary><pre>{fields.filter(field=>field.name==='text').map(field=>field.value).join('\n\n')}</pre></details>}
 {!locked&&fields&&fields.some(field=>['merchant','date','amount'].includes(field.name))&&<Button variant="outline" disabled={!!feedback.busy} onClick={()=>onUseDetails(id,Object.fromEntries(fields.filter(field=>field.name!=='text').map(field=>[field.name,field.value])))}>Use extracted details</Button>}
 <p className="cw-muted">Use the original receipt to verify the extraction. Correct any expense details in the expense editor.</p>{doc.status==='needs_review'&&!locked&&<><label className="cw-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I checked these details against the original receipt.</span></label><Button disabled={!confirmed||fields===null||!!feedback.busy} onClick={()=>void feedback.run('confirm',async()=>{await onlineCommand(p,'document.confirm',id);onConfirmed()})}>{feedback.busy==='confirm'?'Confirming…':'Confirm receipt review'}</Button></>}
 <Feedback error={feedback.error} notice={feedback.notice}/></section>;
}
function Issue({issue,locked,expense,onResolve,onEdit}:{issue:Reconciliation['issues'][number];locked:boolean;expense?:Entity;onResolve:(resolution:Resolution)=>void;onEdit:()=>void}){
 const [explanation,setExplanation]=useState('');
 return <div className="cw-issue"><p>{issue.message}</p>{!locked&&(issue.code==='authorized_item_unaccounted'?<Button variant="outline" onClick={()=>onResolve({type:'not_used',value:issue.authorizationItemId!})}>Mark not used</Button>:issue.code==='over_authorization'?<div className="cw-explanation"><Field label="Explain the additional cost"><Textarea value={explanation} onChange={e=>setExplanation(e.target.value)} maxLength={4000} placeholder="Describe why the actual cost exceeded the plan."/></Field><Button variant="outline" disabled={explanation.trim().length<8} onClick={()=>onResolve({type:'explanation',value:explanation.trim()})}>Save explanation</Button></div>:issue.code==='itinerary_changed'&&expense?<Button variant="outline" onClick={()=>onResolve({type:'confirmed_date',value:text(expense.data.incurredOn)})}>Confirm {displayDate(expense.data.incurredOn)}</Button>:<Button variant="outline" onClick={onEdit}>{issue.action}</Button>)}</div>;
}
