'use client';
import {useRef,useState,type FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {financialProfileSchema,type FinancialProfile} from '@/packages/contracts/financial-readiness';
import {parseFinancialMoney,financialInputMoney} from '@/packages/domain/financial-readiness/money';
import {payCadenceLabels} from '@/packages/domain/financial-readiness/calculate';
import {FinancialMoneyField as MoneyField} from './money-field';
type Draft={cadence:FinancialProfile['cadence'];pay:string;tsp:string;spending:string;expenses:{id:string;name:string;amount:string}[];emergencyBalance:string;emergencyTarget:string;emergencyMonthly:string;goalKind:FinancialProfile['goal']['kind'];goalName:string;goalBalance:string;goalTarget:string;goalMonthly:string;goalMonth:string;separationMonth:string;priority:FinancialProfile['surplusPriority']};
const goalNames={separation:'Separation fund',education:'Education fund',home:'Home fund',other:'My savings goal'};
function draftFrom(p?:FinancialProfile):Draft{return p?{cadence:p.cadence,pay:financialInputMoney(p.takeHomePerPaycheckMinor),tsp:financialInputMoney(p.tspPerPaycheckMinor),spending:financialInputMoney(p.monthlySpendingMinor),expenses:p.expenses.map(e=>({id:e.id,name:e.name,amount:financialInputMoney(e.monthlyAmountMinor)})),emergencyBalance:financialInputMoney(p.emergency.balanceMinor),emergencyTarget:financialInputMoney(p.emergency.targetMinor),emergencyMonthly:financialInputMoney(p.emergency.monthlyContributionMinor),goalKind:p.goal.kind,goalName:p.goal.name,goalBalance:financialInputMoney(p.goal.balanceMinor),goalTarget:financialInputMoney(p.goal.targetMinor),goalMonthly:financialInputMoney(p.goal.monthlyContributionMinor),goalMonth:p.goal.targetMonth||'',separationMonth:p.separationMonth||'',priority:p.surplusPriority}:{cadence:'twice_monthly',pay:'',tsp:'0',spending:'0',expenses:[{id:crypto.randomUUID(),name:'',amount:''}],emergencyBalance:'0',emergencyTarget:'',emergencyMonthly:'0',goalKind:'separation',goalName:'Separation fund',goalBalance:'0',goalTarget:'',goalMonthly:'0',goalMonth:'',separationMonth:'',priority:'emergency_first'}}
export function FinancialIntake({initial,busy,onSave,onCancel}:{initial?:FinancialProfile;busy:boolean;onSave:(p:FinancialProfile)=>void;onCancel?:()=>void}){
 const [d,setDraft]=useState(()=>draftFrom(initial)),[step,setStep]=useState(0),[error,setError]=useState('');const heading=useRef<HTMLHeadingElement>(null);
 function change<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(v=>({...v,[key]:value}));setError('')}
 function money(value:string,label:string){const amount=parseFinancialMoney(value);if(amount===null)throw new Error(`Enter ${label} as dollars and cents, such as 1,300.00.`);return amount}
 function expenses(){return d.expenses.filter(e=>e.name.trim()||e.amount.trim()).map(e=>{if(!e.name.trim())throw new Error('Name each bill or essential cost.');return {id:e.id,name:e.name,monthlyAmountMinor:money(e.amount,e.name)}})}
 function move(next:number){setStep(next);setError('');requestAnimationFrame(()=>heading.current?.focus())}
 function submit(e:FormEvent){e.preventDefault();try{
  const pay=money(d.pay,'take-home pay'),tsp=money(d.tsp||'0','payroll TSP'),spending=money(d.spending,'everyday spending'),bills=expenses();
  if(step===0){move(1);return}
  const p=financialProfileSchema.parse({currency:'USD',cadence:d.cadence,takeHomePerPaycheckMinor:pay,tspPerPaycheckMinor:tsp,monthlySpendingMinor:spending,expenses:bills,emergency:{balanceMinor:money(d.emergencyBalance,'current emergency savings'),targetMinor:money(d.emergencyTarget,'the emergency target'),monthlyContributionMinor:money(d.emergencyMonthly,'monthly emergency saving')},goal:{kind:d.goalKind,name:d.goalName,balanceMinor:money(d.goalBalance,'current goal savings'),targetMinor:money(d.goalTarget,'the goal target'),monthlyContributionMinor:money(d.goalMonthly,'monthly goal saving'),targetMonth:d.goalMonth||null},separationMonth:d.separationMonth||null,surplusPriority:d.priority});onSave(p);
 }catch(e){setError(e instanceof Error&&'issues'in e?'Check your goal name, target amount, and dates.':e instanceof Error?e.message:'Check your entries')}}
 function expenseChange(id:string,key:'name'|'amount',value:string){change('expenses',d.expenses.map(e=>e.id===id?{...e,[key]:value}:e))}
 return <form className="finance-form" onSubmit={submit}>
  <p className="finance-step">{step+1} of 2 · {step===0?'Pay and monthly costs':'Savings and your next chapter'}</p><h2 ref={heading} tabIndex={-1}>{step===0?'Start with what you have.':'Where do you want to get?'}</h2>
  <fieldset disabled={busy}>
  {step===0?<>
   <div className="finance-form-row"><div className="finance-field"><label htmlFor="finance-cadence">How often are you paid?</label><select id="finance-cadence" value={d.cadence} onChange={e=>change('cadence',e.target.value as Draft['cadence'])}>{Object.entries(payCadenceLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div><MoneyField id="finance-pay" label="Take-home per paycheck" value={d.pay} onChange={v=>change('pay',v)} hint="The amount deposited after taxes and payroll deductions."/></div>
   <MoneyField id="finance-tsp" label="TSP already deducted per paycheck (optional)" value={d.tsp} onChange={v=>change('tsp',v)} required={false} hint="For reference only. This is already excluded from take-home pay, so we will not deduct it again."/>
   <h3>Bills and essential costs</h3><p className="finance-hint">Monthly amounts for housing, debt payments, groceries, transportation, and other necessities.</p>
   <div className="finance-expenses">{d.expenses.map((e,i)=><div className="finance-expense-row" key={e.id}><div className="finance-field"><label htmlFor={`expense-${e.id}`}>Cost {i+1}</label><Input id={`expense-${e.id}`} value={e.name} maxLength={80} placeholder="For example, rent" onChange={ev=>expenseChange(e.id,'name',ev.target.value)}/></div><MoneyField id={`amount-${e.id}`} label={`Monthly amount for cost ${i+1}`} value={e.amount} required={Boolean(e.name.trim())} onChange={v=>expenseChange(e.id,'amount',v)}/><button type="button" className="finance-text-button" aria-label={`Remove cost ${i+1}`} onClick={()=>change('expenses',d.expenses.filter(x=>x.id!==e.id))}>Remove</button></div>)}</div>
   <button type="button" className="finance-text-button" disabled={d.expenses.length>=25} onClick={()=>change('expenses',[...d.expenses,{id:crypto.randomUUID(),name:'',amount:''}])}>+ Add a cost</button>
   <MoneyField id="finance-spending" label="Monthly everyday spending allowance" value={d.spending} onChange={v=>change('spending',v)} hint="Flexible spending after essential costs. Do not include the same expense twice."/>
  </>:<>
   <div className="finance-form-row"><div className="finance-field"><label htmlFor="finance-goal-kind">What are you saving for?</label><select id="finance-goal-kind" value={d.goalKind} onChange={e=>{const kind=e.target.value as Draft['goalKind'];setDraft(p=>({...p,goalKind:kind,goalName:p.goalName===goalNames[p.goalKind]?goalNames[kind]:p.goalName}))}}><option value="separation">Leaving the military</option><option value="education">Education or training</option><option value="home">A home</option><option value="other">Another goal</option></select></div><div className="finance-field"><label htmlFor="finance-goal-name">Name your goal</label><Input id="finance-goal-name" value={d.goalName} required maxLength={100} onChange={e=>change('goalName',e.target.value)}/></div></div>
   <div className="finance-form-row"><div className="finance-field"><label htmlFor="finance-separation">Separation month (optional)</label><input type="month" id="finance-separation" value={d.separationMonth} onChange={e=>change('separationMonth',e.target.value)}/></div><div className="finance-field"><label htmlFor="finance-goal-month">Goal deadline (optional)</label><input type="month" id="finance-goal-month" value={d.goalMonth} onChange={e=>change('goalMonth',e.target.value)}/><p className="finance-hint">For a separation fund, leaving this blank uses your separation month.</p></div></div>
   <div className="finance-form-row"><MoneyField id="finance-goal-target" label="Goal amount" value={d.goalTarget} onChange={v=>change('goalTarget',v)}/><MoneyField id="finance-goal-balance" label="Already saved toward this goal" value={d.goalBalance} onChange={v=>change('goalBalance',v)}/></div>
   <MoneyField id="finance-goal-monthly" label="Monthly saving already planned for this goal" value={d.goalMonthly} onChange={v=>change('goalMonthly',v)}/>
   <h3>Your emergency fund</h3><p className="finance-hint">Choose your own target. Keep this balance separate from money counted toward the goal above.</p>
   <div className="finance-form-row"><MoneyField id="finance-emergency-target" label="Emergency fund target" value={d.emergencyTarget} onChange={v=>change('emergencyTarget',v)}/><MoneyField id="finance-emergency-balance" label="Current emergency savings" value={d.emergencyBalance} onChange={v=>change('emergencyBalance',v)}/></div>
   <MoneyField id="finance-emergency-monthly" label="Monthly emergency saving already planned" value={d.emergencyMonthly} onChange={v=>change('emergencyMonthly',v)}/>
   <div className="finance-field"><label htmlFor="finance-priority">If there is money left, prioritize</label><select id="finance-priority" value={d.priority} onChange={e=>change('priority',e.target.value as Draft['priority'])}><option value="emergency_first">Emergency fund, then my goal</option><option value="goal_first">My goal, then emergency savings</option><option value="keep_available">Keep it available for now</option></select><p className="finance-hint">We suggest amounts using this choice. You decide what to save.</p></div>
  </>}
  </fieldset>
  {error&&<p className="finance-error" role="alert">{error}</p>}
  <div className="finance-controls"><Button type="submit" disabled={busy}>{busy?'Saving…':step===0?'Continue':'Show my plan'}</Button>{step===1&&<button type="button" className="finance-text-button" disabled={busy} onClick={()=>move(0)}>Back</button>}{onCancel&&<button type="button" className="finance-text-button" disabled={busy} onClick={onCancel}>Cancel</button>}</div>
  <p className="finance-fine">Manual entry · USD. No bank or payroll connection. Your plan is private to your account in this workspace; no account numbers or statements are needed.</p>
 </form>;
}
