'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import type {FinancialPlan,FinancialProfile} from '@/packages/contracts/financial-readiness';
import {financialMoney as money} from '@/packages/domain/financial-readiness/money';
import {financialResources} from '@/packages/domain/financial-readiness/resources';
const monthLabel=(month:string)=>new Date(`${month}-01T00:00:00Z`).toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'});
export function FinancialSummary({plan,busy,onEdit,onCheckIn,onApply}:{plan:FinancialPlan;busy:boolean;onEdit:()=>void;onCheckIn:()=>void;onApply:(p:FinancialProfile)=>void}){
 const [view,setView]=useState<'paycheck'|'month'>('paycheck');const p=plan.profile,c=plan.calculation;
 const topUp=c.emergencyTopUpMinor+c.goalTopUpMinor,latest=plan.checkIns[0];
 const apply=()=>onApply({...p,emergency:{...p.emergency,monthlyContributionMinor:p.emergency.monthlyContributionMinor+c.emergencyTopUpMinor},goal:{...p.goal,monthlyContributionMinor:p.goal.monthlyContributionMinor+c.goalTopUpMinor}});
 return <div className="finance-summary">
  <div className="finance-toolbar"><p>Plan for {monthLabel(c.asOfMonth)}</p><div><button className="finance-text-button" disabled={busy} onClick={onEdit}>Adjust my plan</button><Button variant="outline" disabled={busy} onClick={onCheckIn}>Update balances</Button></div></div>
  {latest&&latest.month!==c.asOfMonth&&<p className="finance-notice">Your last balance check-in was {monthLabel(latest.month)}. Update your balances to see current progress.</p>}
  {c.monthlyDeficitMinor>0&&<section className="finance-notice finance-warning" aria-labelledby="finance-shortfall"><h2 id="finance-shortfall">Your plan needs {money(c.monthlyDeficitMinor)} more per month.</h2><p>Your costs and chosen saving amounts exceed your take-home pay. Review costs, spending, or saving amounts before relying on the forecast. We have not assumed you can save money that is not available.</p><button className="finance-text-button" disabled={busy} onClick={onEdit}>Review my numbers</button></section>}
  <section aria-labelledby="finance-budget-title"><h2 id="finance-budget-title">Your money this month</h2><dl className="finance-ledger">
   <div><dt>Take-home pay <small>{c.regularPaychecksPerMonth} regular paycheck{c.regularPaychecksPerMonth===1?'':'s'}</small></dt><dd>{money(c.monthlyTakeHomeMinor)}</dd></div>
   <div><dt>Bills and essential costs</dt><dd>− {money(c.monthlyEssentialsMinor)}</dd></div><div><dt>Everyday spending</dt><dd>− {money(p.monthlySpendingMinor)}</dd></div><div><dt>Saving already planned <small>Emergency fund + {p.goal.name}</small></dt><dd>− {money(p.emergency.monthlyContributionMinor+p.goal.monthlyContributionMinor)}</dd></div>
   <div className="finance-ledger-total"><dt>{c.monthlyUnassignedMinor>=0?'Available before extra saving':'Monthly shortfall'}</dt><dd>{money(Math.abs(c.monthlyUnassignedMinor))}</dd></div>
  </dl>
  {p.cadence==='weekly'||p.cadence==='biweekly'?<p className="finance-hint">We budget with {c.regularPaychecksPerMonth} paychecks per month. Extra-paycheck months are excluded from commitments and forecasts. Your annualized monthly average is {money(c.averageMonthlyTakeHomeMinor)}.</p>:null}
  <details className="finance-details"><summary>See entered costs and payroll TSP</summary><ul>{p.expenses.map(e=><li key={e.id}><span>{e.name}</span><span>{money(e.monthlyAmountMinor)} / month</span></li>)}</ul><p>TSP: {money(p.tspPerPaycheckMinor)} per paycheck ({money(c.monthlyTspMinor)} in a regular month), already withheld. It is not subtracted from take-home pay a second time.</p><a href={financialResources.tsp.url} target="_blank" rel="noopener noreferrer">Understand military TSP contributions ↗</a></details>
  </section>
  <section className="finance-goal" aria-labelledby="finance-goal-title"><h2 id="finance-goal-title">{p.goal.name}</h2><div className="finance-progress-label"><span>{money(p.goal.balanceMinor)} of {money(p.goal.targetMinor)} saved</span><strong>{c.goalProgressPercent}%</strong></div><progress aria-label={`Savings progress for ${p.goal.name}`} max={100} value={c.goalProgressPercent}/>
   {c.monthsToSeparation!==null&&<p className="finance-hint">{c.monthsToSeparation>0?`${c.monthsToSeparation} calendar months until separation (${monthLabel(p.separationMonth!)}).`:`Separation month: ${monthLabel(p.separationMonth!)}.`}</p>}
   {c.goalStatus==='reached'?<p className="finance-goal-status">You have reached this savings target. Review where you want future contributions to go.</p>:c.goalStatus==='due_now'||c.goalStatus==='overdue'?<p className="finance-goal-status">{c.goalStatus==='overdue'?'The goal deadline has passed.':'Your goal is due this month.'} You still need {money(c.goalGapMinor)}. Adjust the date or plan based on what is realistic.</p>:c.monthsToGoal===null?<p className="finance-muted">Add a goal deadline to calculate the monthly pace you need. You have {money(c.goalGapMinor)} left to save.</p>:<>
    <dl className="finance-forecast"><div><dt>At your current chosen pace</dt><dd>{c.baselineForecastMinor===null?'Budget needs adjustment':`${money(c.baselineForecastMinor)} by ${monthLabel(c.effectiveGoalMonth!)}`}</dd></div><div><dt>Monthly goal saving needed</dt><dd>{money(c.requiredMonthlyGoalMinor!)} total</dd></div></dl>
    {c.goalStatus==='on_track'?<p className="finance-goal-status">Your chosen saving rate is on track if you maintain it.</p>:c.monthlyDeficitMinor===0&&<p className="finance-goal-status">Save an additional <strong>{money(c.additionalMonthlyGoalMinor!)} per month</strong> toward this goal to reach your target.</p>}
   </>}
   {c.goalTopUpMinor>0&&c.suggestedForecastMinor!==null&&c.monthsToGoal!==0&&<p className="finance-muted">With the suggested goal contribution below, the projection is {money(c.suggestedForecastMinor)}. This assumes that monthly rate continues; it is not a current balance.</p>}
   <p className="finance-fine">Calendar-month estimate: contributions start next month. No interest, investment growth, employer match, GI Bill income, or extra paychecks are assumed. Balances are self-reported.</p>
  </section>
  <section aria-labelledby="finance-paycheck-title"><div className="finance-section-head"><h2 id="finance-paycheck-title">{c.monthlyDeficitMinor>0?'Review your set-aside targets':'Give each paycheck a job'}</h2><div className="finance-view-picker" role="group" aria-label="Allocation view"><button type="button" aria-pressed={view==='paycheck'} onClick={()=>setView('paycheck')}>Per paycheck</button><button type="button" aria-pressed={view==='month'} onClick={()=>setView('month')}>Per month</button></div></div>
   <p className="finance-muted">{topUp>0?`Suggested extra saving follows your priority: ${p.surplusPriority==='goal_first'?'goal first, then emergency fund':'emergency fund first, then your goal'}.`:'These amounts follow your entered costs and chosen saving targets.'}</p>
   <table className="finance-allocation-table"><caption>{view==='paycheck'?`Set aside from each ${money(p.takeHomePerPaycheckMinor)} take-home paycheck`:'Set-aside targets for a regular month'}</caption><thead><tr><th scope="col">Where it goes</th><th scope="col">Amount</th></tr></thead><tbody>{c.allocations.map(a=><tr key={a.id}><th scope="row">{a.label}{a.id==='emergency'&&c.emergencyTopUpMinor>0&&<small>Includes {money(c.emergencyTopUpMinor)} extra / month</small>}{a.id==='goal'&&c.goalTopUpMinor>0&&<small>Includes {money(c.goalTopUpMinor)} extra / month</small>}</th><td>{money(view==='paycheck'?a.perPaycheckMinor:a.monthlyMinor)}</td></tr>)}</tbody><tfoot><tr><th scope="row">Total planned</th><td>{money(view==='paycheck'?c.perPaycheckRequiredMinor:c.allocations.reduce((sum,a)=>sum+a.monthlyMinor,0))}</td></tr></tfoot></table>
   {topUp>0&&c.monthlyDeficitMinor===0&&<div className="finance-controls"><Button disabled={busy} onClick={apply}>{busy?'Saving…':'Use these saving amounts'}</Button><span className="finance-hint">Updates your plan only. No money is transferred.</span></div>}
   <p className="finance-fine">These are set-aside targets, not a bill-payment calendar. Check due dates against actual paydays. Revisit the plan when income or costs change, or an emergency target is reached.</p>
  </section>
  <section aria-labelledby="finance-progress-title"><h2 id="finance-progress-title">Your reported progress</h2><p className="finance-muted">Emergency fund: {money(p.emergency.balanceMinor)} of your {money(p.emergency.targetMinor)} target.</p><details className="finance-details"><summary>Balance check-in history</summary><table className="finance-history"><caption>Latest reported balance in each month · up to 24 months</caption><thead><tr><th scope="col">Month / goal</th><th scope="col">Goal savings</th><th scope="col">Emergency</th></tr></thead><tbody>{plan.checkIns.map(check=><tr key={check.month}><th scope="row">{monthLabel(check.month)}<small>{check.goalName}</small></th><td>{money(check.goalBalanceMinor)}</td><td>{money(check.emergencyBalanceMinor)}</td></tr>)}</tbody></table></details></section>
  <section className="finance-resources" aria-labelledby="finance-help-title"><h2 id="finance-help-title">Support for the next step</h2><p>Use official information to understand your options.</p><ul>{Object.values(financialResources).filter(r=>p.goal.kind==='education'||r!==financialResources.education).map(r=><li key={r.url}><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title} ↗</a><small>{r.organization}</small></li>)}</ul><Link href="/dashboard/transition">Explore work, training, or education after service →</Link></section>
  <p className="finance-fine">A budgeting tool based on your entries, not investment or tax advice. Ouranos does not verify bank balances, change payroll contributions, determine benefits, or move money.</p>
 </div>;
}
